---
abstract: 'define functions and methods with parameter lists ("subroutine signatures")'
author:
  - 'Lukas Mai <l.mai@web.de>'
build_requires:
  Dir::Self: '0'
  Hash::Util: '0.07'
  Test::Fatal: '0'
  Test::More: '0'
  constant: '0'
  strict: '0'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::Find: '0'
  File::Spec: '0'
  strict: '0'
  warnings: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Function-Parameters
no_index:
  directory:
    - t
    - inc
    - xt
requires:
  Carp: '0'
  Scalar::Util: '0'
  XSLoader: '0'
  perl: '5.014000'
  warnings: '0'
resources:
  repository: git://github.com/mauke/Function-Parameters
version: '2.001003'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
